config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :things
  resources :news
  root 'pages#Home'
  get 'nowy' => 'news#index'
  get 'new' => 'news#index'
  get 'onas' => 'pages#about'
  get 'kontakt' => 'pages#contact'
  get 'spektakle' => 'pages#spektakle'
  get 'warsztaty' => 'pages#warsztaty'
  get 'specjalne' => 'pages#specjalne'
  get 'osoby' => 'pages#osoby'

  get 'things' => 'things#index'

end

app/models/news.rb
class News < ActiveRecord::Base

  has_attached_file :foto_news, styles: { medium_news: "750x750#", thumb_news: "75x75#", kolo: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :foto_news, content_type: /\Aimage\/.*\Z/

  belongs_to :user
end

app/models/thing.rb
class Thing < ActiveRecord::Base
has_attached_file :foto, styles: { medium: "750x1080>", thumb: "75x108>", kolo: "100x100#" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/

has_attached_file :foto2, styles: { medium: "750x1080>", thumb: "75x108>", kolo: "100x100#" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :foto2, content_type: /\Aimage\/.*\Z/

has_attached_file :foto3, styles: { medium: "750x1080>", thumb: "75x108>", kolo: "100x100#" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :foto3, content_type: /\Aimage\/.*\Z/

belongs_to :user

extend FriendlyId
friendly_id :title, use: :slugged

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :things
         has_many :news
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
def menu
  $spektakle = Thing.all.where(rodzaj: 'spektakl')
  $warsztaty = Thing.all.where(rodzaj: 'warsztat')
  $specjalne = Thing.all.where(rodzaj: 'specjalny')
end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :edit, :update, :destroy]
  before_action :menu#Application



  # GET /news
  # GET /news.json
  def index
    @news = News.all.order(updated_at: :desc)
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:co, :czego, :czas1, :czas2, :czas3, :foto_news)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :menu#Application

  def Home
      @news = News.order(updated_at: :desc).first(4)
  end
  def about
  end
  def contact
  end

  def spektakle
            @things = Thing.all.where(rodzaj: 'spektakl')


  end
  def warsztaty
            @things = Thing.all.where(rodzaj: 'warsztat')
  end
  def specjalne
            @things = Thing.all.where(rodzaj: 'specjalne')
  end
  def osoby

  end

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :menu#Application





  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
        format.js { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
        format.js { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:title, :opisik, :opis, :meta, :recenzja, :rodzaj, :foto, :foto2, :foto3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <%= link_to 'sztuczka', root_path, class:'navbar-brand'%>
      <%= link_to 'niusy', news_index_path, class:'navbar-brand'%>
      <%= link_to 'spektakle', spektakle_path, class:'navbar-brand'%>
      <%= link_to 'warsztaty', warsztaty_path, class:'navbar-brand'%>
      <%= link_to 'specjalne', specjalne_path, class:'navbar-brand'%>
      <%= link_to 'osoby', osoby_path, class:'navbar-brand'%>
      <%= link_to 'logout',destroy_user_session_path, :method => :delete, class:'navbar-brand'%>
<br>
<% if flash[:notice] %>
  <li class="navbar-brand"><%= flash[:notice] %></li>
<% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_menu.html.erb
<div class="menu">
    <div class="dropup " style="position:relative">
    	<button class="btn btn-primary btn-circle btn-xl dropdown-toggle" data-toggle="dropdown">MENU <span class="caret"></span></button>
    	<ul class="dropdown-menu">
    		<li>
    			<a class=" btn btn-default btn-circle btn-xl animsition-link trigger right-caret">SPEKTAKLE</a>
    			<ul class="dropdown-menu sub-menu">
    <% $spektakle.each do |thing| %>
    <li><%= link_to image_tag(thing.foto.url(:kolo), class: 'img-circle'), thing_path(thing), class: ' animsition-link'%></li>
          <% end %>
  	</ul>
    		</li>

        <li>
          <a class=" btn btn-default btn-circle btn-xl animsition-link trigger right-caret">WARSZTATY</a>
          <ul class="dropdown-menu sub-menu">
    <% $warsztaty.each do |thing| %>
        <li><%= link_to image_tag(thing.foto.url(:kolo), class: 'img-circle'), thing_path(thing), class: 'animsition-link'%></li>
    <% end %>
    </ul>
        </li>

        <li>
          <a class=" btn btn-default btn-circle btn-xl animsition-link trigger right-caret">SPECJALNE</a>
          <ul class="dropdown-menu sub-menu">
    <% $specjalne.each do |thing| %>
    <li><%= link_to image_tag(thing.foto.url(:kolo), class: 'img-circle'), thing_path(thing), class: ' animsition-link'%></li>
    <% end %>
    </ul>
        </li>

        <li><%= link_to 'O NAS', onas_path, class: 'btn btn-default btn-circle btn-xl animsition-link'%></li>
        <li><%= link_to 'NIUSY', root_path, class: 'btn btn-default btn-circle btn-xl animsition-link'%></li>



    	</ul>
    </div>
</div> <!-- koniec menu -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sztuczka</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=PT+Sans:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="animsition">

<% if current_user %>
<%= render 'layouts/header' %>
<% end %>

<%= render 'layouts/menu' %>


<div class="container">
<%= yield %>
</div>
</div>
</body>
</html>

app/views/news/_form.html.erb
<%= simple_form_for @news, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.input :foto_news, as: :file %>
  <%= f.input :co %>
  <%= f.input :czego %>
  <%= f.input :czas1 %>
  <%= f.input :czas2 %>
  <%= f.input :czas3 %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                news_index_path, :class => 'btn btn-default' %>
<% end %>

app/views/news/edit.html.erb
<%- model_class = News -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/news/index.html.erb
<% if current_user %>
<%= link_to t('.new', :default => t("helpers.links.new")),
    new_news_path,
    :class => 'btn btn-circle btn-xl btn-primary ' %>
<% end %>

<table class="table ">
  <thead>
    <tr>
      <th>co</th>
      <th>czego</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td>  <%= link_to image_tag(news.foto_news.url(:kolo), class: 'img-circle'), news_path(news)%></td>
        <td><%= news.co %></td>
        <td><%= news.czego %></td>
        <% if current_user %>

        <td>
          <td><%= link_to 'show', news_path(news), :class => 'btn btn-default btn-lg btn-circle '  %></td>
        <td>  <%= link_to 'edit', edit_news_path(news), :class => 'btn btn-warning btn-lg btn-circle' %></td>
          <td><%= link_to 'destroy', news_path(news),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-lg btn-circle btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/news/new.html.erb
<%- model_class = News -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/news/show.html.erb
<%- model_class = News -%>

<div class="col-md-6 ">
    <%= image_tag @news.foto_news.url(:medium_news), :class => 'img-responsive' %>
  </div>
  <div class="col-md-6 ">

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:co) %>:</strong></dt>
  <dd><%= @news.co %></dd>
  <dt><strong><%= model_class.human_attribute_name(:czego) %>:</strong></dt>
  <dd><%= @news.czego %></dd>
  <dt><strong><%= model_class.human_attribute_name(:czas1) %>:</strong></dt>
  <dd><%= @news.czas1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:czas2) %>:</strong></dt>
  <dd><%= @news.czas2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:czas3) %>:</strong></dt>
  <dd><%= @news.czas3 %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              news_index_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_news_path(@news), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              news_path(@news),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/pages/Home.html.erb
<div id="carousel-example-generic" class="carousel slide col-md-6 " data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
          <% @news.each do |news| %>
    <div class="item">
    <%= image_tag news.foto_news.url(:medium_news), :class => 'img-responsive' %>
      <div class="carousel-caption niusy-tlo">
        <p><span><%= news.co %></span></p>
        <p><span><%= news.czego %></span></p>
        <p><span><%= news.czas1 %></span></p>
      </div>
    </div>

    <% end %>
</div>
</div>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/contact.html.erb
<h1>contact</h1>

app/views/pages/osoby.html.erb
<h1>osoby</h1>
<% if current_user %>
<%= link_to t('.new', :default => t("helpers.links.new")),
    new_thing_path,
    :class => 'btn btn-circle btn-xl btn-primary ' %>
<% end %>

app/views/pages/specjalne.html.erb
<% if current_user %>
<%= link_to t('.new', :default => t("helpers.links.new")),
    new_thing_path,
    :class => 'btn btn-circle btn-xl btn-primary ' %>
<% end %>
<table class="table">
  <thead>
    <tr>

      <th></th>
      <th><%= :title %></th>
      <th><%= :opisik %></th>

      <th><%= :meta %></th>

      <th><%= :rodzaj %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody >
    <% @things.each do |thing| %>
      <tr class="jeden-opis">

        <td class="foto">
        <%= link_to image_tag(thing.foto.url(:kolo), class: 'img-circle'), thing_path(thing)%></td>
        <td><%= thing.title %></td>
        <td><%= thing.opisik.first(280) %></td>

        <td><%= thing.meta.first(280) %></td>

        <td><%= thing.rodzaj %></td>



        <% if current_user %>
        <td>
          <%= link_to 'Show', thing_path(thing), :class => 'btn btn-default btn-lg btn-circle ' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_thing_path(thing), :class => 'btn btn-default btn-warning btn-lg btn-circle ' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      thing_path(thing),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-lg btn-danger btn-circle ' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/spektakle.html.erb
<% if current_user %>
<%= link_to t('.new', :default => t("helpers.links.new")),
    new_thing_path,
    :class => 'btn btn-circle btn-xl btn-primary ' %>
<% end %>
<table class="table">
  <thead>
    <tr>

      <th></th>
      <th><%= :title %></th>
      <th><%= :opisik %></th>

      <th><%= :meta %></th>

      <th><%= :rodzaj %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody >
    <% @things.each do |thing| %>
      <tr class="jeden-opis">

        <td class="foto">
        <%= link_to image_tag(thing.foto.url(:kolo), class: 'img-circle'), thing_path(thing)%></td>
        <td><%= thing.title %></td>
        <td><%= thing.opisik %></td>

        <td><%= thing.meta.first(280) %></td>

        <td><%= thing.rodzaj %></td>



        <% if current_user %>
        <td>
          <%= link_to 'Show', thing_path(thing), :class => 'btn btn-default btn-lg btn-circle ' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_thing_path(thing), :class => 'btn btn-default btn-warning btn-lg btn-circle ' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      thing_path(thing),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-lg btn-danger btn-circle ' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/warsztaty.html.erb
<% if current_user %>
<%= link_to t('.new', :default => t("helpers.links.new")),
    new_thing_path,
    :class => 'btn btn-circle btn-xl btn-primary ' %>
<% end %>
<table class="table">
  <thead>
    <tr>

      <th></th>
      <th><%= :title %></th>
      <th><%= :opisik %></th>

      <th><%= :meta %></th>

      <th><%= :rodzaj %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody >
    <% @things.each do |thing| %>
      <tr class="jeden-opis">

        <td class="foto">
        <%= link_to image_tag(thing.foto.url(:kolo), class: 'img-circle'), thing_path(thing)%></td>
        <td><%= thing.title %></td>
        <td><%= thing.opisik.first(280) %></td>

        <td><%= thing.meta.first(280) %></td>

        <td><%= thing.rodzaj %></td>



        <% if current_user %>
        <td>
          <%= link_to 'Show', thing_path(thing), :class => 'btn btn-default btn-lg btn-circle ' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_thing_path(thing), :class => 'btn btn-default btn-warning btn-lg btn-circle ' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      thing_path(thing),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-lg btn-danger btn-circle ' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/things/_form.html.erb
<%= simple_form_for @thing, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :foto, as: :file %>
  <%= f.input :foto2, as: :file %>
  <%= f.input :foto3, as: :file %>


<%= image_tag @thing.foto.url(:thumb) %>
<%= image_tag @thing.foto2.url(:thumb) %>
<%= image_tag @thing.foto3.url(:thumb) %>


<br>
  <%= f.input :title %>

  <%= f.input :opisik %>

  <%= f.input :opis %>

  <%= f.input :meta %>

  <%= f.input :recenzja %>


  <%= f.input :rodzaj, as: :radio_buttons,
  collection: ['spektakl', 'warsztat', 'specjalny'] %>



  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                things_path, :class => 'btn btn-default' %>
<% end %>

app/views/things/edit.html.erb
<%- model_class = Thing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/things/index.html.erb
<%- model_class = Thing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
        <% if current_user %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_thing_path,
            :class => 'btn btn-circle btn-xl btn-primary ' %>
        <% end %>
<table class="table">
  <thead>
    <tr>

      <th></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:opisik) %></th>

      <th><%= model_class.human_attribute_name(:meta) %></th>

      <th><%= model_class.human_attribute_name(:rodzaj) %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody >
    <% @things.each do |thing| %>
      <tr class="jeden-opis">

        <td class="foto">
        <%= link_to image_tag(thing.foto.url(:kolo), class: 'img-circle'), thing_path(thing)%></td>
        <td><%= thing.title %></td>
        <td><%= thing.opisik.first(280) %></td>

        <td><%= thing.meta.first(280) %></td>

        <td><%= thing.rodzaj %></td>



        <% if current_user %>
        <td>
          <%= link_to 'Show', thing_path(thing), :class => 'btn btn-default btn-lg btn-circle ' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_thing_path(thing), :class => 'btn btn-default btn-warning btn-lg btn-circle ' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      thing_path(thing),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-lg btn-danger btn-circle ' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/things/new.html.erb
<%- model_class = Thing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/things/rr.html.erb
<% @things.each do |thing| %>
<li><a class=" btn btn-default btn-circle btn-xl animsition-link" href="#"><%= thing.title %></a></li>
<% end %>

app/views/things/show.html.erb
<%- model_class = Thing -%>


<div id="carousel-example-generic" class="carousel slide col-md-6 fotos" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag @thing.foto.url(:medium), :class => 'img-responsive' %>
    </div>
    <div class="item">
      <%= image_tag @thing.foto2.url(:medium), :class => 'img-responsive' %>
    </div>
    <div class="item">
      <%= image_tag @thing.foto3.url(:medium), :class => 'img-responsive' %>
    </div>

  </div>

</div>





<div class="col-md-6 textowo">



  <div class="panel-body"><h2><%= @thing.title %></h2></div>

  <div class="panel-body"><%= simple_format(@thing.opisik) %></div>

<div class="btn btn-default btn-circle btn-xl poka1 "><%= model_class.human_attribute_name(:opis) %></div>
<div class="btn btn-default btn-circle btn-xl poka3"><%= model_class.human_attribute_name(:recenzja) %></div>
<div class="btn btn-default btn-circle btn-xl poka2"><%= model_class.human_attribute_name(:meta) %></div>

  <div class=" znik1"><%= @thing.opis %></div>

  <div class=" znik2"><%= simple_format(@thing.meta) %></div>

  <div class=" znik3"><%= @thing.recenzja %></div>


</div>

<!--
<%= link_to t('.back', :default => t("helpers.links.back")),
              things_path, :class => 'btn btn-default btn-circle btn-xl'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_thing_path(@thing), :class => 'btn btn-default btn-circle btn-xl' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              thing_path(@thing),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger btn-circle btn-xl' %> -->
</div> <!-- koniec col-md-6 -->